import os
import time
import mujoco
import mujoco.viewer

# NOTE: To run this script, you need to install mujoco and download assets.
# pip install mujoco

def create_demo_scene():
    """
    Creates a temporary MJCF XML string that:
    1. Loads a placeholder 'kitchen' environment (represented by a simple floor/box here).
    2. Imports a Franka Emika Panda robot (requires internet to fetch or local file).
    
    Since we cannot auto-download the proprietary World Labs asset in this script,
    we mock the 'World Labs Env' with a complex static geometry.
    """
    
    # This XML defines a scene with a Franka robot and a static environment
    # We use a built-in floor and some geometric primitives to represent the 'Kitchen'
    # In a real workflow, you would replace the <geom type="box"...> with:
    # <mesh file="path/to/downloaded_world_labs_kitchen.glb"/>
    
    xml = """
    <mujoco model="world_labs_demo">
        <statistic center="0.3 0 0.4" extent="0.8"/>
        
        <visual>
            <headlight diffuse="0.6 0.6 0.6" ambient="0.1 0.1 0.1" specular="0 0 0"/>
            <rgba haze="0.15 0.25 0.35 1"/>
            <global azimuth="120" elevation="-20"/>
        </visual>

        <asset>
            <!-- 
               PLACEHOLDER: In production, download your World Labs .glb/.obj file 
               and uncomment the line below:
               <mesh name="kitchen_mesh" file="worlds/api_renders/domestic_kitchen.glb"/>
            -->
            <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
            <texture type="2d" name="groundplane" builtin="checker" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3" width="100" height="100"/>
            <material name="groundplane" texture="groundplane" texrepeat="60 60" reflectance="0.2"/>
        </asset>

        <worldbody>
            <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
            <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
            
            <!-- 
                 MOCK KITCHEN ENVIRONMENT
                 This represents the "static" world generated by World Labs.
                 In a real integration, this would be your imported mesh.
            -->
            <body name="kitchen_counter" pos="0.5 0 0.4">
                <geom type="box" size="0.3 0.6 0.4" rgba="0.8 0.8 0.8 1" friction="1 0.005 0.0001"/>
                <geom name="sink" type="box" size="0.2 0.15 0.1" pos="0 -0.3 0.4" rgba="0.7 0.7 0.7 1"/>
            </body>

            <!-- 
                 FRANKA EMIKA PANDA
                 We embedded a simplified kinematic chain here for demonstration.
                 For full physics, use the official mujoco_menagerie XMLs.
            -->
            <body name="panda_link0" pos="0 0 0">
                <!-- <geom type="mesh" mesh="link0_col" /> Visuals omitted for demo -->
                <geom type="cylinder" size="0.1 0.1" rgba="1 1 1 1"/> 
                
                <body name="panda_link1" pos="0 0 0.333">
                    <joint name="joint1" axis="0 0 1" range="-2.8973 2.8973"/>
                    <geom type="capsule" fromto="0 0 0 0 0 -0.15" size="0.06" rgba="1 1 1 1"/>
                    
                    <body name="panda_link2" pos="0 0 0" quat="0.707 -0.707 0 0">
                        <joint name="joint2" axis="0 0 1" range="-1.7628 1.7628"/>
                         <geom type="capsule" fromto="0 0 0 0 0 -0.15" size="0.06" rgba="1 1 1 1"/>
                         
                         <!-- End Effector mock -->
                         <body name="end_effector" pos="0 0 0.5">
                            <geom type="sphere" size="0.05" rgba="1 0 0 1"/>
                         </body>
                    </body>
                </body>
            </body>
        </worldbody>
    </mujoco>
    """
    return xml

def main():
    print("🌍 World Labs -> MuJoCo Integration Demo")
    print("----------------------------------------")
    print("This script simulates how to load a generated environment into MuJoCo.")
    print("Note: Since we cannot download private assets securely in this script,")
    print("we are loading a procedural scene that REPRESENTS the structure.")
    print("\nLoading simulation...")

    # 1. Generate the XML (in a real app, you'd load a file)
    xml = create_demo_scene()

    # 2. Parse the Model
    try:
        model = mujoco.MjModel.from_xml_string(xml)
    except ValueError as e:
        print(f"Error loading MJCF: {e}")
        return

    data = mujoco.MjData(model)

    # 3. Launch Viewer
    print("👀 Launching Viewer... (Close window to exit)")
    with mujoco.viewer.launch_passive(model, data) as viewer:
        # Simple simulation loop
        start_time = time.time()
        while viewer.is_running():
            step_start = time.time()
            
            # Simple control: Sine wave on Joint 1
            data.ctrl = [0] * model.nu # If we had actuators
            # Manually actuate for demo (kinematic override for visualization)
            data.qpos[0] = 0.5 * (1 + 0.5 *  mujoco.mju_sin(time.time()))

            mujoco.mj_step(model, data)
            viewer.sync()
            
            # Keep meaningful frame rate
            time_until_next_step = model.opt.timestep - (time.time() - step_start)
            if time_until_next_step > 0:
                time.sleep(time_until_next_step)

if __name__ == "__main__":
    main()
